T_b( "<table frame='all'>" );
T_b( "\n" );
T_b( "<title>" );
T_b( T_xmlify( doc_tbl->title ) );
T_b( "</title>" );
T_b( "\n" );
T_b( "<tgroup cols='" );
T_b( T_s( doc_tbl->num_cols ) );
T_b( "' align='left' colsep='0' rowsep='0'>" );
T_b( "\n" );
