T_b("#include \"");
T_b(te_file->registers);
T_b(".");
T_b(te_file->hdr_file_ext);
T_b("\"");
T_b("\n");
T_b("/*----------------------------------------------------------------------------");
T_b("\n");
T_b(" ");
T_b("* component ISR/polling interface");
T_b("\n");
T_b(" ");
T_b("*--------------------------------------------------------------------------*/");
T_b("\n");
T_b("void ");
T_b(te_c->Name);
T_b("_POLL( void );");
T_b("\n");
T_b("void ");
T_b("\n");
T_b(te_c->Name);
T_b("_POLL( void )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("static char outCountP = 0;");
T_b("\n");
T_b("  ");
T_b("static volatile u4_t ");
T_b(te_c->Name);
T_b("_status_register;");
T_b("\n");
T_b("  ");
T_b("u4_t ");
T_b(te_c->Name);
T_b("_status = ");
T_b(te_c->Name);
T_b("_status_register;");
T_b("\n");
T_b("  ");
T_b("/*");
T_b("\n");
T_b("   ");
T_b("* Based on the value in the status register, read parameters and");
T_b("\n");
T_b("   ");
T_b("* invoke the appropriate port message.");
T_b("\n");
T_b("   ");
T_b("*/");
T_b("\n");
