T_b("/*----------------------------------------------------------------------------");
T_b("\n");
T_b(" ");
T_b("* File:  ");
T_b(te_ee->file);
T_b(".");
T_b(te_file->hdr_file_ext);
T_b("\n");
T_b(" ");
T_b("*");
T_b("\n");
T_b(" ");
T_b("* Description:");
T_b("\n");
T_b(" ");
T_b("* Methods for bridging to an external entity.");
T_b("\n");
T_b(" ");
T_b("*");
T_b("\n");
T_b(" ");
T_b("* External Entity:  ");
T_b(te_ee->Name);
T_b(" (");
T_b(te_ee->Key_Lett);
T_b(")");
T_b("\n");
T_b(" ");
T_b("* ");
T_b(te_ee->Descrip);
T_b("\n");
T_b(" ");
T_b("* ");
T_b(te_copyright->body);
T_b("\n");
T_b(" ");
T_b("*--------------------------------------------------------------------------*/");
T_b("\n");
T_b("#ifndef ");
T_b(te_ee->file);
T_b("_");
T_b(te_file->hdr_file_ext);
T_b("\n");
T_b("#define ");
T_b(te_ee->file);
T_b("_");
T_b(te_file->hdr_file_ext);
T_b("\n");
T_b(te_target->c2cplusplus_linkage_begin);
T_b("\n");
T_b(includes->body);
T_b("\n");
T_b(ee_body->body);
T_b("");
T_b(te_target->c2cplusplus_linkage_end);
T_b("\n");
T_b("#endif   /* ");
T_b(te_ee->file);
T_b("_");
T_b(te_file->hdr_file_ext);
T_b(" */");
T_b("\n");
