T_b(ws);
T_b(te_select_related->result_var);
T_b(" = ( 0 != ");
T_b(te_lnk->left);
T_b(" ) ? (");
T_b(te_lnk->te_classGeneratedName);
T_b(" *) ");
T_b(te_set->get_any);
T_b("( &");
T_b(te_lnk->left);
T_b("->");
T_b(te_lnk->linkage);
T_b(" ) : 0;");
T_b("\n");
