T_b(ws);
T_b("{");
T_b(te_select_related->result_var);
T_b(" = 0;");
T_b("\n");
T_b(ws);
T_b("{");
T_b(te_class->GeneratedName);
T_b(" * selected = ( 0 != ");
T_b(te_lnk->left);
T_b(" ) ? ");
T_b(te_lnk->left);
T_b("->");
T_b(te_lnk->linkage);
T_b(" : 0;");
T_b("\n");
T_b(ws);
T_b("if ( ( 0 != selected ) && ");
T_b(te_select_related->where_clause);
T_b(" ) {");
T_b("\n");
T_b(ws);
T_b("  ");
T_b(te_select_related->result_var);
T_b(" = selected;");
T_b("\n");
T_b(ws);
T_b("}}}");
T_b("\n");
