T_b("/*----------------------------------------------------------------------------");
T_b("\n");
T_b(" ");
T_b("* File:  ");
T_b(te_file->nvs);
T_b(".");
T_b(te_file->hdr_file_ext);
T_b("\n");
T_b(" ");
T_b("*");
T_b("\n");
T_b(" ");
T_b("* External Entity:  'Non-Volatile Storage' (NVS)");
T_b("\n");
T_b(" ");
T_b("*");
T_b("\n");
T_b(" ");
T_b("* Description:");
T_b("\n");
T_b(" ");
T_b("* Non-Volatile Storage (NVS) is used to persist class instances and");
T_b("\n");
T_b(" ");
T_b("* link instances for MC-3020 applications.");
T_b("\n");
T_b(" ");
T_b("*");
T_b("\n");
T_b(" ");
T_b("* ");
T_b(te_copyright->body);
T_b("\n");
T_b(" ");
T_b("*--------------------------------------------------------------------------*/");
T_b("\n");
T_b("#ifndef ");
T_b(te_file->nvs);
T_b("_");
T_b(te_file->hdr_file_ext);
T_b("\n");
T_b("#define ");
T_b(te_file->nvs);
T_b("_");
T_b(te_file->hdr_file_ext);
T_b("\n");
T_b(te_target->c2cplusplus_linkage_begin);
T_b("\n");
T_b("#define NVS_RETURN_SUCCESS    0 /* All is well.                    */");
T_b("\n");
T_b("#define NVS_ERROR_BAD_OPEN   -1 /* Could not open file.            */");
T_b("\n");
T_b("#define NVS_ERROR_ITEM_LONG  -2 /* Data item is too long.          */");
T_b("\n");
T_b("#define NVS_ERROR_BAD_SEEK   -3 /* Could not seek correctly.       */");
T_b("\n");
T_b("#define NVS_ERROR_BAD_WRITE  -4 /* File did not write correctly.   */");
T_b("\n");
T_b("#define NVS_ERROR_NOT_FOUND  -5 /* Did not find searched record.   */");
T_b("\n");
T_b("#define NVS_ERROR_BAD_READ   -6 /* Read incorrect length of data.  */");
T_b("\n");
T_b("#define NVS_ERROR_NO_ROOM    -7 /* Not enough room for insert.     */");
T_b("\n");
T_b("#define NVS_ERROR_LENGTH     -8 /* Length not correct.             */");
T_b("\n");
T_b("#define NVS_STORAGE_SIZE 0xffff");
T_b("\n");
T_b("#define NVS_MAX_ITEMS      4000");
T_b("\n");
T_b("#define NVS_MAX_ITEM_SIZE   512");
T_b("\n");
T_b("i_t ");
T_b(te_prefix->result);
T_b("NVS_checksum( i_t, i_t );");
T_b("\n");
T_b("i_t ");
T_b(te_prefix->result);
T_b("NVS_defrag( void );");
T_b("\n");
T_b("i_t ");
T_b(te_prefix->result);
T_b("NVS_remove( u4_t, i_t, c_t const *, i_t );");
T_b("\n");
T_b("i_t ");
T_b(te_prefix->result);
T_b("NVS_format( void );");
T_b("\n");
T_b("i_t ");
T_b(te_prefix->result);
T_b("NVS_initialize( void );");
T_b("\n");
T_b("i_t ");
T_b(te_prefix->result);
T_b("NVS_insert( u4_t, i_t, c_t const *, i_t );");
T_b("\n");
T_b("i_t ");
T_b(te_prefix->result);
T_b("NVS_next( u4_t *, i_t, c_t *, i_t * );");
T_b("\n");
T_b("i_t ");
T_b(te_prefix->result);
T_b("NVS_select( u4_t, i_t, c_t *, i_t );");
T_b("\n");
T_b("i_t ");
T_b(te_prefix->result);
T_b("NVS_space_available( void );");
T_b("\n");
T_b("i_t ");
T_b(te_prefix->result);
T_b("NVS_space_total( void );");
T_b("\n");
T_b("i_t ");
T_b(te_prefix->result);
T_b("NVS_space_used( void );");
T_b("\n");
T_b("i_t ");
T_b(te_prefix->result);
T_b("NVS_update( u4_t, i_t, c_t const *, i_t );");
T_b("\n");
T_b("i_t ");
T_b(te_prefix->result);
T_b("NVS_version( i_t, i_t );");
T_b("\n");
T_b(te_target->c2cplusplus_linkage_end);
T_b("\n");
T_b("#endif   /* ");
T_b(te_file->nvs);
T_b("_");
T_b(te_file->hdr_file_ext);
T_b(" */");
T_b("\n");
