CC=gcc
# gdb - CFLAGS=-Wno-pointer-to-int-cast -g 
CFLAGS=-Wno-pointer-to-int-cast 
SOURCES := $(shell ls *.c)
OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=m2x

all:  $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	@$(CC) $(CFLAGS) $^ -o $@

.o:
	$(CC) $(CFLAGS) -c $<
