= Add New Marks

xtUML Project Implementation Note

== 1 Abstract

This note documents additional marks added to BridgePoint to support WACA
(Ada model compiler) features not previously specified but found in production
models.

== 2 Introduction and Background

A mark joins a model compiler feature to a model element.  Some features exist
in WACA that are not used by SWATS and that were not specified as part of
Caledonia.  This work adds those marks and feature associations.

== 3 Requirements

=== 3.1 oaid_derived_ols

'oaid_derived_ols' shall emit text following the pattern of the
'oaid_derived' mark.

=== 3.2 product

The 'product' mark shall be available to the following model elements:

* terminator service
* class
* class operation
* domain function
* scenario

Text shall be emitted that indicates 'PRODUCT' and the parametric product
modifier.

=== 3.3 initialised, non_initialised

The 'initialised' and 'non_initialised' marks shall be appliable to classes.

=== 3.4 system_address

The 'system_address' mark shall be supported against classes.  It takes a
string argument indicating a base address for the class.

== 4 Work Required

=== 4.1 oaid_derived_ols

Modify `routine.render_marking` to add support for this variation of the
OAID configurations.

=== 4.2 product

=== 4.3 initialised, non_initialised

Modify `object.render_marking` to add support for this variation of object
memory placement and setup.  These tags also support a parameter which, if
present, will be output following the tag group and tag name.

=== 4.4 system_address

. Modify `object.render_marking` to add support for this variation of object
  memory initialization.
. Add a template containing 'System_Address_Group,System_Address,<pragma
  value>'.

== 5 Implementation Comments

== 6 Unit Test

== 7 User Documentation

== 8 Code Changes

- fork/repository:  cortlandstarrett/mc
- branch:  12115_new_marks

----
 Put the file list here
----

== 9 Document References

. [[dr-1]] https://support.onefact.net/issues/12115[12115 - Add additional marks not found in SWATS.]

---

This work is licensed under the Creative Commons CC0 License

---
