= Add New Marks

xtUML Project Implementation Note

== 1 Abstract

This note documents additional marks added to BridgePoint to support WACA
(Ada model compiler) features not previously specified but found in production
models.

== 2 Introduction and Background

A mark joins a model compiler feature to a model element.  Some features exist
in WACA that are not used by SWATS and that were not specified as part of
Caledonia.  This work adds those marks and feature associations.

== 3 Requirements

=== 3.1 oaid_derived_ols

'oaid_derived_ols' shall emit text following the pattern of the
'oaid_derived' mark.

=== 3.2 product

The 'product' mark shall be available to the following model elements:

* terminator service
* class
* class operation
* domain function
* scenario

Text shall be emitted that indicates 'PRODUCT' and the parametric product
modifier.

=== 3.3 initialised, non_initialised

The 'initialised' and 'non_initialised' marks shall be appliable to classes.

=== 3.4 system_address

The 'system_address' mark shall be supported against classes.  It takes a
string argument indicating a base address for the class.

== 4 Work Required

=== 4.1 oaid_derived_ols

Modify `routine.render_marking` to add support for this variation of the
OAID configurations.

=== 4.2 product

Modify the `render_marking` operations for `routine` and `operation`
to recognize the product tag.

Modify `masloout` to match `Required Operation` with only the executable
property name (and not require a full signature).

=== 4.3 initialised, non_initialised

Modify `object.render_marking` to add support for this variation of object
memory placement and setup.  These tags also support a parameter which, if
present, will be output following the tag group and tag name.

=== 4.4 system_address

. Modify `object.render_marking` to add support for this variation of object
  memory initialization.
. Add a template containing 'System_Address_Group,System_Address,<pragma
  value>'.

== 5 Implementation Comments

`maslout` required modification due to the behavior of the marking editor.
When marking a Required or Provided Operation, only the name is required
(and useful).  The marking editor provides a pathkey containing only the
name and not the return type and parameters.

I left the `message_getsignature` function in place, even though now it is
not being used.  I suspect it will be needed at some point.

== 6 Unit Test

Test using the TAGS model supplied by user.

== 7 User Documentation

== 8 Code Changes

- fork/repository:  cortlandstarrett/mc
- branch:  12115_new_marks

----
 doc/notes/12115_new_marks/12115_new_marks_int.adoc                | 107 ++++++++++++++++++++++++++
 model/masl/gen/wasl/t.object_address.wasl                         |   1 +
 model/masl/gen/wasl/t.object_product.wasl                         |   1 +
 model/masl/models/masl/masl/object/object.xtuml                   |  35 ++++++++++++++++--
 model/masl/models/masl/masl/routine/routine.xtuml                 |  24 +++++++++++++
 model/masl/models/masl/maslpopulation/genfile/genfile.xtuml       |  14 +++++++-
 model/masl/src/wasl/t.object_address.wasl                         |   3 ++
 model/masl/src/wasl/t.object_product.wasl                         |   4 +++
 model/maslout/models/maslout/lib/xtuml2masl/maslout/maslout.xtuml |  64 +++++++++++++++++++++-----
 9 files changed, 237 insertions(+), 16 deletions(-)
----

== 9 Document References

. [[dr-1]] https://support.onefact.net/issues/12115[12115 - Add additional marks not found in SWATS.]

---

This work is licensed under the Creative Commons CC0 License

---
