= MASL exporter emits warnings for core types

xtUML Project Implementation Note

:sectnums:

== Abstract

Benign but confusing warnings are being issued during the export of MASL.
This work resolves the root cause and simplifies the way BridgePoint
manages MASL-specific data types.

== Introduction and Background

When Raven was originally developed, MC-3020 was not able to process
UUIDs and 128 integers.  Now, MC-302 can.  This opens an option for
linking imported MASL types to BridgePoint more naturally.

== Requirements

=== Eliminate warning emitted due to unbound types.

== Work Required

=== Detect Unbound Types More Accurately
First, check if the type is based on 'MASLtype'. If it is, this is a
type reference type and should never be qualified with the containing
domain name.

Second, check if the package is directly off the system. In this case,
it is assumed that the user understands that the package is not contained
by a component so it will _not_ be qualified. A special case that is
important for this check is the 'types' package which contains MASL core
types and is generated directly off the system. This check prevents types
in this package from ever being qualified.

=== Dump String UUIDs
Now that MC-3020 understands UUIDs both as integers and as strings, dump
the string version from the instance dumper.

=== Link Globals
=== Link Referentials (R114)
Instead of linking via IDLINK, ...

== Implementation Comments

== Unit Test

== User Documentation

== Code Changes

- fork/repository:  cortlandstarrett/mc
- branch:  10195_typewarn

```
 arc/q.sys.populate.arc                                            |   3 +-
 bin/masl2xtuml                                                    |   4 +-
 doc/process/templates/int_template.adoc                           |  12 ++-
 mcmc/arlan/o.oal                                                  |   3 +-
 model/escher/gen/ooaofooa.c                                       |  15 ++--
 model/escher/gen/ooaofooa_c_orig                                  |  17 ++--
 model/escher/models/escher/mcmc/afun/afun.xtuml                   |   3 +-
 model/maslin/gen/IDLINK_bridge.c                                  | 140 -----------------------------
 model/maslin/gen/domain.mark                                      |   1 +
 model/maslin/gen/masl2xtuml_O_ATTR_class.c                        | 273 --------------------------------------
 model/maslin/gen/masl2xtuml_S_UDT_class.c                         | 138 ----------------------------
 model/maslin/gen/sys_user_co.c                                    |  42 +++++++--
 model/maslin/gen/sys_user_co.h                                    |   4 +-
 model/maslin/models/maslin/lib/masl2xtuml/masl2xtuml.xtuml        |  25 +++++-
 model/maslin/models/maslin/m2x/m2x.xtuml                          | 176 ++++++------------------------------
 model/maslin/models/maslin/m2x/ooapopulation/ooapopulation.xtuml  | 177 +++++++++++++++++++++++-------------
 model/maslout/models/maslout/lib/xtuml2masl/maslout/maslout.xtuml |  47 +++++-----
 schema/Globals.xtuml                                              | 260 ++++++++++++++++++++++++++++++++++++++
 18 files changed, 518 insertions(+), 822 deletions(-)
```

== Document References

In this section, list all the documents that the reader may need to refer to.
Give the full path to reference a file.

. [[dr-1]] https://support.onefact.net/issues/10195[10195 - MASL exporter emits warnings for core types]

---

This work is licensed under the Creative Commons CC0 License

---
