= Analyze building mcmc with ciera

xtUML Project Analysis Note

== 1 Abstract

This note is written to analyze building mcmc with the ciera model compiler. It
will address the following:

. benefits of building with ciera
. challenges of building with ciera
. shortcomings of ciera that would need to be resolved
. generation process changes (e.g. changes in the RSL2OAL converter, template generation, etc.)
. ways to improve escher
. potential implications

== 2 Introduction and Background

=== Escher and mcmc

Many years ago, a portion of the MC-3020 model compiler which is implemented in
RSL was factored out and converted to an xtUML model with actions defined in
OAL. The portion that was factored out was the portion that translated the
action language. Actions were translated to C and then "rolled up" into a string
attribute of an extension class "Action Block Anchor" (`TE_ABA`). The output of
the instance population is the same SQL statements that were loaded with the new
classes created and the instances that were already translated excluded. Doing
this improves performance dramatically as the "Value" and "Body" (`V_` and
`ACT_`) subsystems which represent parsed OAL are by far the most numerous in
the instance population. The number of instances loaded and processed by the
Python based RSL interpreter (`pyrsl`) is orders of magnitude less than before.

The factored out portion was dubbed the "escher" project and produces an
executable application called "mcmc". Escher is itself compiled with MC-3020 and
compiled to a binary executable for each platform to which BridgePoint is
targeted. This was done because MC-3020 is by far the most feature complete
model compiler freely available, and it was convenient to do so, but there are
several problems with the project that require handwritten code and special
modifications to get it to run. MC-3020 was designed for small, fast embedded
applications -- not string processing.

MC-3020 is still fully maintained as a set of RSL queries and templates. An
internal tool exists to convert the archetypes from RSL to OAL and import them
into the escher project in BridgePoint. Another internal tool is used to
generate C templates from RSL templates which are included at compile time by
the C preprocessor.

=== ciera

In the last few years a new model compiler has been under development which
targets Java. ciera is designed to be easy to use and integrate into other
applications and produces Java which runs on the Java SE 8 platform with no
third party dependencies. Java as a programming language itself offers many
benefits for string processing operations required by a model compiler as well
as being able to run natively on the Eclipse platform which BridgePoint targets.

ciera is a private project under active development. It started as a personal
project to experiment with modeled model compiler concepts and has evolved to a
relatively feature complete model compiler. It is not open source, but the
creator intends to put it in the open space at some point.

== 3 Requirements

=== 3.1 Analysis shall be performed to address each item in the list in section <<1 Abstract>>

== 4 Analysis

During analysis ciera version 1.1.1 was used to actually build a modified escher
project. The resulting Java application was integrated into the MC-3020 flow and
used to generate C source for the MicrowaveOven example project. The source
generated by Java mcmc was semantically identical to the source generated by the
current production version of mcmc, and the behavior of the generated application
was identical. This experiment has been leveraged to produce the following
analysis.

=== 4.1 Benefits of building with ciera

==== 4.1.1 Less handwritten code and hacks

One of the weaknesses of using MC-3020 to translate a model based model compiler
is string processing. MC-3020 was designed to operate on low memory targets and
rely on static memory allocation. As such, strings should be kept short and a
max string length is expected to be marked.

A model compiler application has a vast dynamic range of string sizes. From less
than ten characters to contain a variable name to thousands of characters to
hold an entire code body. This can be done effectively in C, but MC-3020 was not
designed for it. Because of this there are several areas in the code where
special string processing is handwritten in to handle strings that are known to
be quite large. This handwritten code is an altered version of a generated file
which is versioned in git and must be maintained with every edit.

A model compiler which can better handle large and small strings with dynamic
allocation is better, because it removes the need for special processing in
handwritten code. ciera provides this ability as it is built to target Java
which automatically handles string allocation.

==== 4.1.2 Portability

BridgePoint is built on the Eclipse platform (which runs on the Java virtual
machine), however there are a few BridgePoint utilities that are packaged and
deployed "outside" Eclipse. mcmc is one of these utilities. Currently the
BridgePoint engineering team packages and ships three different versions of
mcmc -- 64 bit Linux, 64 bit Windows, and 64 bit macOS. A model compiler that
could generate an application which can run on the Eclipse platform is more
portable and saves the BridgePoint team the maintenance cost of testing on
multiple operating systems.

==== 4.1.3 Escher generation process

ciera implements a template conversion mechanism, so there would no longer be a
need to run the template converter application and commit templates in the
target language.

=== 4.2 Challenges of building with ciera

==== 4.2.1 Loading and dumping instances

As a model compiler, the escher project needs to support loading and dumping
instances. ciera has a mechanism to generate a loader/dumper that can load
instances from SQL insert statements and dump them to a file or standard out.
The loader tends to be relatively strict and does not cope with associations
which are not formalized. There are some marks used for marking certain
attributes and classes as non-persistent, but there is no mark for identifying
classes to be loaded but not persisted. For the escher project it is key that
certain classes be excluded from the output to reduce the population size for
`pyrsl`.

==== 4.2.2 Templating

ciera has a mechanism to translate RSL templates and include them in OAL. Escher
also requires a facility for parsing RSL variable substitutions in string
literals. For example the following OAL:

```
name = "Levi";
msg = "Hello ${name}!";
LOG::LogInfo(message:msg);
```

would produce output:

```
Hello Levi!
```

Literal string processing was introduced as a feature in ciera version 1.1.1.

==== 4.2.3 Marking

The escher project loads marks from a file called "m.txt" and processes them one
by one. A handwritten EE can be introduced to do the same parsing using regular
expressions.

=== 4.3 Shortcomings of ciera that would need to be resolved

==== 4.3.1 Comments in templates

The ciera template mechanism does not support comments in templates. This should
be added as a feature. <<dr-2>>

==== 4.3.2 Partial dumping

As mentioned in <<4.2.1 Loading and dumping instances>>, ciera does not have
a mechanism for preventing classes from being dumped. There are reasonable ways to
implement this with project specific handwritten code, but this should be added
as a feature. <<dr-3>>

==== 4.3.3 Existence of `a.xtuml`

Currently, mcmc loads a file called "a.xtuml" if it exists and reads from
standard in otherwise. ciera does not have a utility for checking if a file
exists. A built in EE should be introduced to do simple file operations (open,
close, read, write, exists, etc). <<dr-4>>

==== 4.3.4 `ARCH::exit(code:0)`

ciera provides a standard implementation of `ARCH::shutdown()` which finishes
the current activity and then initiates a shutdown. An `exit` bridge should be
added which can exit the process immediately with an error code. This is
currently provided by the `T::` bridge for use in escher. <<dr-5>>

==== 4.3.5 `current_state`

ciera does not allow an attribute to be named `current_state`. This is to
avoid confusion with the architectural attribute `current_state` created in
active classes. ciera should translate attributes with this name as long as they
are not typed with the special type "state<State_Model>". <<dr-6>>

==== 4.3.6 R2066 (TE_INSTANCE, TE_SET, TE_EXTENT)

In the translation extensions model, R2066 between TE_INSTANCE, TE_SET, and
TE_EXTENT is not formalized and these classes do not have identifiers. ciera
cannot handle this case. The MC-3020 loader does not have a problem with this,
because these instances are never loaded. ciera should implement a mechanism for
partial loading corresponding to the partial dumping described in  <<4.3.2
Partial dumping>>. <<dr-3>>

=== 4.4 Generation process changes (e.g. changes in the RSL2OAL converter, template generation, etc.)

Some changes would need to be made to the RSL2OAL converter such that when
escher is generated from the MC-3020 archetypes, parseable and correct code is
produced.

==== 4.4.1 `TEMP::` instead of `T::`

ciera provides an implementation of the templating bridge that differs slightly
from the one provided in mcshared used by escher. Some of the bridges are named
differently and notably, the bridges in `T::` which handle string substitutions
(capitalize, underscore, etc) are consolidated into one bridge "sub" which takes
an argument "format" to specify which formatting operations to perform. The
"include" bridge also has a different signature in order to enable ciera to pass
in context objects to a template. The converter would need to be upgraded to
produce the correct signatures for the TEMP EE provided by ciera.

==== 4.4.2 `LOG::LogInfo` instead of `T::print`

The `T::` EE provides a bridge "print". `TEMP::` in ciera does not have this
bridge. `LOG::LogInfo` should be produced in these situations instead.

==== 4.4.3 `ARCH::exit` instead of `T::exit`

The `T::` EE provides a bridge "exit". `TEMP::` in ciera does not have this
bridge. `ARCH::exit` should be produced in these situations instead. See section
<<4.3.4 `ARCH::exit(code:0)`>>

==== 4.4.4 Multiple return statements

Some functions in the OAL version of escher have multiple return statements one
after another. This is an artifact of the way RSL returns values with fragments.
In Java this produces a compiler error since the return statements following the
first are unreachable code. The archetypes should be updated to remove these
unnecessary returns.

=== 4.5 Ways to improve escher

==== 4.5.1 Statement population

In the routine that populates the translation extensions from the xtUML instance
population, an assumption is made about the order of statements. This should be
tightened up to assure that the statements are in the correct order.

=== 4.6 Potential implications

==== 4.6.1 Proof of concept for ciera

This work could represent the first "real" application that ciera has been used
for. Escher is no small model and is a good proving ground for a new model
compiler.

==== 4.6.2 Usage for MASL tool chain

If ciera is successful in improving the escher project, it could bring the same
benefits to the MASL tools (`m2x`, `x2m`, `masl`).

==== 4.6.3 Risk of using ciera

ciera is free to download and use, however it is not fully open source. The
creator intends to make it open source at some point, but at the moment it is
not. Relying on a closed-source application in the BridgePoint build poses some
risk.

=== 4.7 Performance metrics

The experimental Java version of escher was built and used to build escher.
This was done to evaluate the preformance impact. Escher may be the biggest
model (with the most action language) that we build with MC-3020 on a regular
basis.

The experiment was performed by running pre-builder once. The model compiler was
then timed from launch to end of code generation. This included the time for
`pyrsl` to load the instance population and generate the structural code. The
decision to include `pyrsl` in the timing is that one of the key functions of
escher is to pare down the instance population to improve performance of
`pyrsl`. The experiment was done on a 2017 model MacBook Pro with 16GB of RAM
running macOS Mojave. For the Linux tests, a VirtualBox VM running Ubuntu 18.04
LTS hosted on the MacBook Pro was used. For some of the tests, the model data
was accessed in a folder shared with the Ubuntu guest but physically located on
the Mac using VirtualBox filesharing mechanisms. For other tests, all file
system accesses were contained within the context of the local file system on
the guest OS. Due to a `flex` dependency, the binary version of mcmc cannot be
run on macOS when templating is used. The results are ordered from fastest to
slowest.

|===
| mcmc on Linux VM (reading local file system)         | 0m39.663s
| mcmc.java on Linux VM (reading local file system)    | 0m46.889s
| mcmc.java on macOS                                   | 0m49.564s
| mcmc on Linux VM (reading file system on macOS)      | 0m52.112s
| mcmc.java on Linux VM (reading file system on macOS) | 2m6.460s
|===

You can see from these results that the Java version of mcmc is slower than the
compiled binary version in all cases. It is also clear that a large portion of
the execution time is loading and persisting instances. This can be seen in the
difference between executions using the bridged file system on the VM versus a
local file system. It seems that the Java version is affected more by slow file
IO than the compiled version.

== 5 Work Required

5.1 The changes to ciera described in section 4.3 must be made. In some cases
workarounds could be implemented.

5.2 The archetype and conversion changes described in section 4.4 must be made.

5.3 Design must be performed to package and implement escher as a ciera project
considering the possibility of delivery as an Eclipse plugin.

== 6 Acceptance Test

N/A

== 7 Document References

. [[dr-1]] https://support.onefact.net/issues/11571[11571 - Analyze building mcmc with ciera]
. [[dr-2]] http://support.ciera.io:4209/issues/75[75 - support comments in templates]
. [[dr-3]] http://support.ciera.io:4209/issues/83[83 - Support partial dumping and partial loading of classes]
. [[dr-4]] http://support.ciera.io:4209/issues/81[81 - Add file system utility]
. [[dr-5]] http://support.ciera.io:4209/issues/80[80 - Add ability to exit immediately with error code]
. [[dr-6]] http://support.ciera.io:4209/issues/84[84 - Allow "curent_state" to be translated]

---

This work is licensed under the Creative Commons CC0 License

---
