= Analyze building mcmc with ciera

xtUML Project Analysis Note

== 1 Abstract

This note is written to analyze building mcmc with the ciera model compiler. It
will address the following:

. benefits of building with ciera
. challenges of building with ciera
. shortcomings of ciera that would need to be resolved
. generation process changes (e.g. changes in the RSL2OAL converter, template generation, etc.)
. ways to improve escher
. potential implications

== 2 Introduction and Background

Many years ago, a portion of the MC-3020 model compiler which is implemented in
RSL was factored out and converted to an xtUML model with actions defined in
OAL. The portion that was factored out was the portion that translated the
action language. Actions were translated to C and then "rolled up" into a string
attribute of an extension class "Action Block Anchor" (`TE_ABA`). The output of
the instance population is the same SQL statements that were loaded with the new
classes created and the instances that were already translated excluded. Doing
this improves performance dramatically as the "Value" and "Body" (`V_` and
`ACT_`) subsystems which represent parsed OAL are by far the most numerous in
the instance population. The number of instances loaded and processed by the
Python based RSL interpreter (`pyrsl`) is orders of magnitude less than before.

The factored out portion was dubbed the "escher" project and produces and
executable application called "mcmc". Escher is itself compiled with MC-3020 and
compiled to a binary executable for each platform to which BridgePoint is
targeted. This was done because MC-3020 is by far the most feature complete
model compiler freely available and it was convenient to do so, but there are
several problems with the project that require handwritten code and special
modifications to get it to run. MC-3020 was designed for small, fast embedded
applications -- not string processing.

In the last few years a new model compiler has been under development which
targets Java. ciera is designed to be easy to use and integrate into other
applications and produces Java which runs on the Java SE 8 platform with no
third party dependencies. Java as a programming language itself offers many
benefits for string processing operations required by a model compiler as well
as being able to run natively on the Eclipse platform which BridgePoint targets.

== 3 Requirements

=== 3.1 Analysis shall be performed to address each item in the list in section <<1 Abstract>>

== 4 Analysis

During analysis ciera version 1.1.1 was used to actually build a modified escher
project. The resulting Java application was integrated into the MC-3020 flow and
used to generate C source for the MicrowaveOven example project. The source
generated by Java mcmc was semantically identical to the source generated by the
current production version of mcmc and the behavior of the generated application
was identical. This experiment has been leveraged to produce the following
analysis.

4.1 Benefits of building with ciera

- less handwritten code/hacks
- portability

4.2 Challenges of building with ciera

- loading/dumping instances
- templating
- marking

4.3 Shortcomings of ciera that would need to be resolved

- comments in templates
- dumping partial populations
- selecting input based on existence of `a.xtuml`
- exit with error code
- `current_state`
- R2066 (TE_INSTANCE, TE_SET, TE_EXTENT)

4.4 Generation process changes (e.g. changes in the RSL2OAL converter, template generation, etc.)

- `TEMP::` instead of `T::`
- `LOG::LogInfo` instead of `T::print`
- `ARCH::shutdown` instead of `T::exit`
- multiple return statements

4.5 Ways to improve escher

- Statement population
- multiple return statements?

4.6 Potential implications

- usage for MASL toolchain
- proof of concept for ciera

== 5 Work Required

TODO

== 6 Acceptance Test

None

== 7 Document References

. [[dr-1]] https://support.onefact.net/issues/11571[11571 - Analyze building mcmc with ciera]

---

This work is licensed under the Creative Commons CC0 License

---
