= Executable element numbering

xtUML Project Design Note

== 1 Abstract
Numbering is required for operations/functions in the MASL and WASL output.  This numbering should be sequentially increased among sibling elements.

== 2 Introduction and Background

Numbering was added for C_EP, SPR_RO and S_SYNC.  This number attribute was initialized to 0 and only ever changed if the user modified the value.

== 3 Requirements
=== 3.1 All executable elements associated with system modeling have a Numb attribute
=== 3.2 Numbering is intialized sequentially
=== 3.3 Numbering is transfered from template elements

== 4 Analysis
In order to support masl and wasl number attributes were added to a few elements. These elements were Functions, Operations and Interface operations. During creation these numbers are always initialized to 0. We need to initialize these numbers sequentially as is done with other element's numbers (i.e, Association).

Additionally when these elements are used as a template to another element that number shall be transferred. For example, when a Function is published to in Interface, the resultant Interface Operation should have the same number value set.

== 5 Design

=== 5.1 Make numbering consistent
For components only C_EP and SPR_RO had the Numb attribute.  To be consistent a Numb attribute is added to SPR_PO, SPR_PS, and SPR_RS.  These attributes are added to both the ooaofooa and mcooa.

=== 5.2 Initialize numbering sequentially
A new operation, initializeSequentialNumber, is added to C_EP, S_SYNC, O_TFR, and D_TSVC.  This operation finds the highest number among the siblings, adds one and sets it to the element.

In all cases that the elements above are created the new operation is called.

=== 5.3 Transfer number
In the case of terminator services the number from the executable property template is transferred.

The same is done for the publishing of a function to an interface operation.

== 6 Design Comments

== 7 User Documentation

== 8 Unit Test
Outline all the unit tests that need to pass and describe the method that you
will use to design and perform the tests.


== 9 Document References

In this section, list all the documents that the reader may need to refer to.
Give the full path to reference a file.

. [[dr-1]] https://support.onefact.net/issues/12053[12053 - headline]

---

This work is licensed under the Creative Commons CC0 License

---
