T_b("extern ");
T_b(te_set->scope);
T_b(te_extent->type);
T_b(" ");
T_b(extent);
T_b(";");
T_b("\n");
if ( te_class->PEIsDefinedInData ) {
T_b("extern ");
T_b(te_class->GeneratedName);
T_b(" ");
T_b(te_class->GeneratedName);
T_b("_instances[ ");
T_b(te_class->GeneratedName);
T_b("_MAX_EXTENT_SIZE ];");
T_b("\n");
}
T_b("extern void ");
T_b(te_class->GeneratedName);
T_b("_FactoryInit();");
T_b("\n");
T_b("extern ");
T_b(te_instance->handle);
T_b(" ");
T_b(te_class->GeneratedName);
T_b("_Create();");
T_b("\n");
T_b("extern void ");
T_b(te_class->GeneratedName);
T_b("_Delete(");
T_b(defaultPrefix);
T_b("_iHandle_t);");
T_b("\n");
T_b("extern int g_");
T_b(te_class->GeneratedName);
T_b("_instanceMax;");
T_b("\n");
T_b("extern int g_");
T_b(te_class->GeneratedName);
T_b("_instanceNum;");
T_b("\n");
