T_b("--ooaofooa_path:");
T_b(diagram->path);
T_b(" diagram.ID:");
T_b(T_s(diagram->ID));
T_b(" ooaofooa_ID:");
T_b(T_s(diagram->ooaofooa_ID));
T_b("\n");
T_b("INSERT INTO GD_MD VALUES (");
T_b(T_s(diagram->ID));
T_b(", ");
T_b(T_s(diagram->Model_Type));
T_b(", ");
T_b(T_s(diagram->ooaofooa_ID));
T_b(", ");
T_b(T_s(diagram->OOA_Type));
T_b(", 0, 0, 1, 1, 1, 12, 1, 0, 0, 0, 0, 0, '4.1.17', '");
T_b(diagram->path);
T_b("');");
T_b("\n");
T_b("INSERT INTO DIM_DIA VALUES (");
T_b(T_s(diagram->ID));
T_b(", '', 1.000000, 4000.000000, 3000.000000, 0);");
T_b("\n");
