T_b("--diagram.ID: ");
T_b(T_s(diagram->ID));
T_b("  ooaofooa_ID: ");
T_b(T_s(diagram->ooaofooa_ID));
T_b("  ooaofooa_path: ");
T_b(diagram->path);
T_b("\n");
T_b("INSERT INTO GD_MD");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(diagram->ID));
T_b(", ");
T_b("\n");
T_b("	");
T_b("8, -- Model_Type");
T_b("\n");
T_b("	");
T_b(T_s(diagram->ooaofooa_ID));
T_b(",  -- the id of the ooaofooa element for ISM this is SM_SM.SM_ID");
T_b("\n");
T_b("	");
T_b("40, -- OOA_TYPE");
T_b("\n");
T_b("	");
T_b("0,");
T_b("\n");
T_b("	");
T_b("0,");
T_b("\n");
T_b("	");
T_b("1,");
T_b("\n");
T_b("	");
T_b("1,");
T_b("\n");
T_b("	");
T_b("1,");
T_b("\n");
T_b("	");
T_b("12,");
T_b("\n");
T_b("	");
T_b("1,   -- grid_on_flag");
T_b("\n");
T_b("	");
T_b("0,   -- x_coordinate");
T_b("\n");
T_b("	");
T_b("0,   -- y_coordinate");
T_b("\n");
T_b("	");
T_b("0,   -- width     ");
T_b("\n");
T_b("	");
T_b("0,   -- height");
T_b("\n");
T_b("	");
T_b("0, ");
T_b("\n");
T_b("	");
T_b("'4->1->17',    -- This is the persistence version (\"4->1->17\" right now)-> This is set only if widgets are present-> It is empty if there are no widgets");
T_b("\n");
T_b("	");
T_b("'");
T_b(diagram->path);
T_b("');");
T_b("\n");
T_b("INSERT INTO DIM_DIA                                     ");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(diagram->ID));
T_b(",");
T_b("\n");
T_b("	");
T_b("'',");
T_b("\n");
T_b("	");
T_b("1.000000,  -- zoom level");
T_b("\n");
T_b("	");
T_b("4000.000000,  -- viewport_x_coordinate - I do not see how this is used. Changes to not seem to do anything");
T_b("\n");
T_b("	");
T_b("3000.000000,  -- viewport_y_coordinate - I do not see how this is used. Changes to not seem to do anything");
T_b("\n");
T_b("	");
T_b("0);  -- null ID");
T_b("\n");
