T_b("--diagram.ID: ");
T_b(T_s(diagram->ID));
T_b("  widget.ID: ");
T_b(T_s(widget->ID));
T_b("   ooaofooa_path: ");
T_b(widget->path);
T_b("\n");
T_b("INSERT INTO GD_GE");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(widget->ID));
T_b(",");
T_b("\n");
T_b("	");
T_b(T_s(diagram->ID));
T_b(",");
T_b("\n");
T_b("	");
T_b(T_s(widget->ooaofooa_ID));
T_b(",   -- This is the ID of SM_STATE");
T_b("\n");
T_b("	");
T_b("41,  -- OOA_Type");
T_b("\n");
T_b("	");
T_b("0,");
T_b("\n");
T_b("	");
T_b("'");
T_b(widget->path);
T_b("'); -- represents_path");
T_b("\n");
T_b("INSERT INTO GD_SHP");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(widget->ID));
T_b(");");
T_b("\n");
T_b("INSERT INTO GD_NCS");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(widget->ID));
T_b(");");
T_b("\n");
T_b("INSERT INTO DIM_ND");
T_b("\n");
T_b("	");
T_b("VALUES (157.000000,  -- width");
T_b("\n");
T_b("	");
T_b("85.000000,           -- heigth");
T_b("\n");
T_b("	");
T_b(T_s(widget->ID));
T_b(");");
T_b("\n");
T_b("INSERT INTO DIM_GE");
T_b("\n");
T_b("	");
T_b("VALUES (7800.000000, -- positionX - This is the x position on the diagram, right goes positive");
T_b("\n");
T_b("	");
T_b("5880.000000,         -- positionY - This is the y position on the diagram, down goes positive");
T_b("\n");
T_b("	");
T_b(T_s(widget->ID));
T_b(",");
T_b("\n");
T_b("	");
T_b("0);  -- Semantic model bridge id. (referential for DIM_SMB.Smb_ID) ");
T_b("\n");
T_b("-- Note: This is odd. In \"UML 2.0 Diagram Interchange, this (DIM_ELE) only has 1 attribute, a represents)");
T_b("\n");
T_b("INSERT INTO DIM_ELE                                   ");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(widget->ID));
T_b(",");
T_b("\n");
T_b("	");
T_b("0,");
T_b("\n");
T_b("	");
T_b("0);  --null id");
T_b("\n");
