T_b("--diagram.ID: ");
T_b(T_s(diagram->ID));
T_b("  widge.ID: ");
T_b(T_s(widget->ID));
T_b("  ooaofooa_path: ");
T_b(widget->path);
T_b("\n");
T_b("INSERT INTO DIM_CON                      -- This represents an the anchor point for the connector");
T_b("\n");
T_b("                                         ");
T_b("-- In this example there are 2 of them because the line is connected to ");
T_b("\n");
T_b("                                         ");
T_b("-- a figure on each end");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(coupler->cID1));
T_b(",");
T_b("\n");
T_b("	");
T_b(T_s(orig_widget->x));
T_b(".000000,                      -- XPosition");
T_b("\n");
T_b("	");
T_b(T_s(orig_widget->y));
T_b(".000000,                      -- YPosition");
T_b("\n");
T_b("	");
T_b(T_s(orig_widget->ID));
T_b(");             -- ID of the widget this coupler is attached to");
T_b("\n");
T_b("INSERT INTO DIM_CON");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(coupler->cID2));
T_b(",        -- This is a second coupler ID that will be generated");
T_b("\n");
T_b("	");
T_b(T_s(dest_widget->x));
T_b(".000000,");
T_b("\n");
T_b("	");
T_b(T_s(dest_widget->y));
T_b(".000000,");
T_b("\n");
T_b("	");
T_b(T_s(orig_widget->ID));
T_b(");            -- ID if the widget this coupler is attached to");
T_b("\n");
T_b("INSERT INTO GD_GE");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(widget->ID));
T_b(",");
T_b("\n");
T_b("	");
T_b(diagram->ID);
T_b(",");
T_b("\n");
T_b("	");
T_b(T_s(widget->ooaofooa_ID));
T_b(",          -- This is the SM_TXN.id");
T_b("\n");
T_b("	");
T_b("42,                              -- OOA_Type");
T_b("\n");
T_b("	");
T_b("0,");
T_b("\n");
T_b("	");
T_b("\"");
T_b(widget->path);
T_b("\");               --example: ClassDiagramOnly::ClassDiagram::class1::Instance State Machine::Unnamed State::No Event Assigned");
T_b("\n");
T_b("	                                 ");
T_b("-- It is the source side that this represents_path represents");
T_b("\n");
T_b("INSERT INTO GD_CON");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(widget->ID));
T_b(",");
T_b("\n");
T_b("	");
T_b("0);        -- null id");
T_b("\n");
T_b("INSERT INTO GD_CTXT");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(coupler->textID1));
T_b(",");
T_b("\n");
T_b("	");
T_b(T_s(widget->ID));
T_b(",");
T_b("\n");
T_b("	");
T_b("1,                               -- Enum the represents the end of the connector for which this is serving as text (start,middle,end)");
T_b("\n");
T_b("	");
T_b("0.000000,                        -- x offset of the connector text from the default position");
T_b("\n");
T_b("	");
T_b("0.000000);                       -- y offset of the connector text from the default position");
T_b("\n");
T_b("INSERT INTO DIM_ND");
T_b("\n");
T_b("	");
T_b("VALUES (0.000000,                -- width");
T_b("\n");
T_b("	");
T_b("0.000000,                        -- height");
T_b("\n");
T_b("	");
T_b(T_s(coupler->textID1));
T_b(");");
T_b("\n");
T_b("INSERT INTO DIM_GE");
T_b("\n");
T_b("	");
T_b("VALUES (0.000000,                -- positionX - This is the x position on the diagram");
T_b("\n");
T_b("	");
T_b("0.000000,                        -- positionY - This is the y position on the diagram");
T_b("\n");
T_b("	");
T_b(T_s(coupler->textID1));
T_b(",");
T_b("\n");
T_b("	");
T_b("0);                              -- Semantic model bridge id. (referential for DIM_SMB.Smb_ID)");
T_b("\n");
T_b("INSERT INTO DIM_ELE");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(coupler->textID1));
T_b(",");
T_b("\n");
T_b("	");
T_b("0,");
T_b("\n");
T_b("	");
T_b("0);                              -- null id");
T_b("\n");
T_b("INSERT INTO GD_CTXT");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(coupler->textID2));
T_b(",");
T_b("\n");
T_b("	");
T_b(T_s(widget->ID));
T_b(",");
T_b("\n");
T_b("	");
T_b("3,                               -- Enum the represents the end of the connector for which this is serving as text (start,middle,end)");
T_b("\n");
T_b("	");
T_b("0.000000,");
T_b("\n");
T_b("	");
T_b("0.000000);");
T_b("\n");
T_b("INSERT INTO DIM_ND");
T_b("\n");
T_b("	");
T_b("VALUES (0.000000,");
T_b("\n");
T_b("	");
T_b("0.000000,");
T_b("\n");
T_b("	");
T_b(T_s(coupler->textID2));
T_b(");");
T_b("\n");
T_b("INSERT INTO DIM_GE");
T_b("\n");
T_b("	");
T_b("VALUES (0.000000,");
T_b("\n");
T_b("	");
T_b("0.000000,");
T_b("\n");
T_b("	");
T_b(T_s(coupler->textID2));
T_b(",");
T_b("\n");
T_b("	");
T_b("0);        -- null id");
T_b("\n");
T_b("INSERT INTO DIM_ELE");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(coupler->textID2));
T_b(",");
T_b("\n");
T_b("	");
T_b("0,");
T_b("\n");
T_b("	");
T_b("0);        -- null id");
T_b("\n");
T_b("INSERT INTO GD_CTXT");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(coupler->textID3));
T_b(", ");
T_b("\n");
T_b("	");
T_b(T_s(widget->ID));
T_b(",");
T_b("\n");
T_b("	");
T_b("2,                                    -- Enum the represents the end of the connector for which this is serving as text (start,middle,end)");
T_b("\n");
T_b("	");
T_b("0.000000,");
T_b("\n");
T_b("	");
T_b("0.000000);");
T_b("\n");
T_b("INSERT INTO DIM_ND");
T_b("\n");
T_b("	");
T_b("VALUES (0.000000,");
T_b("\n");
T_b("	");
T_b("0.000000,");
T_b("\n");
T_b("	");
T_b(T_s(coupler->textID3));
T_b(");");
T_b("\n");
T_b("INSERT INTO DIM_GE");
T_b("\n");
T_b("	");
T_b("VALUES (0.000000,");
T_b("\n");
T_b("	");
T_b("0.000000,");
T_b("\n");
T_b("	");
T_b(T_s(coupler->textID3));
T_b(",");
T_b("\n");
T_b("	");
T_b("0);        -- null id");
T_b("\n");
T_b("INSERT INTO DIM_ELE");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(coupler->textID3));
T_b(",");
T_b("\n");
T_b("	");
T_b("0,");
T_b("\n");
T_b("	");
T_b("0);        -- null id");
T_b("\n");
T_b("INSERT INTO GD_LS");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(coupler->lsID1));
T_b(",");
T_b("\n");
T_b("	");
T_b(T_s(widget->ID));
T_b(",");
T_b("\n");
T_b("	");
T_b("0,        -- null id");
T_b("\n");
T_b("	");
T_b(T_s(coupler->wpID1));
T_b(",       --start waypoint_id");
T_b("\n");
T_b("	");
T_b(T_s(coupler->wpID2));
T_b(");      -- end_watpoint_id");
T_b("\n");
T_b("INSERT INTO DIM_WAY");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(coupler->wpID1));
T_b(", ");
T_b("\n");
T_b("	");
T_b("7633.000000,            -- xposition");
T_b("\n");
T_b("	");
T_b("5843.000000,            --yposition");
T_b("\n");
T_b("	");
T_b(T_s(widget->ID));
T_b(",          ");
T_b("\n");
T_b("	");
T_b("0,        -- this is the \"polyline\" element id");
T_b("\n");
T_b("	");
T_b("0);       -- This is the previous waypoint ID");
T_b("\n");
T_b("INSERT INTO DIM_WAY");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(coupler->wpID2));
T_b(", ");
T_b("\n");
T_b("	");
T_b("7752.000000,  --xposition");
T_b("\n");
T_b("	");
T_b("5843.000000,  --yposition");
T_b("\n");
T_b("	");
T_b(T_s(widget->ID));
T_b(",");
T_b("\n");
T_b("	");
T_b("0,        -- null id");
T_b("\n");
T_b("	");
T_b(T_s(coupler->wpID1));
T_b(");  -- This is the previous waypoint ID");
T_b("\n");
T_b("INSERT INTO DIM_GE");
T_b("\n");
T_b("	");
T_b("VALUES (0.000000,");
T_b("\n");
T_b("	");
T_b("0.000000,");
T_b("\n");
T_b("	");
T_b(T_s(widget->ID));
T_b(",");
T_b("\n");
T_b("	");
T_b("0);        -- null id");
T_b("\n");
T_b("INSERT INTO DIM_ELE");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(widget->ID));
T_b(",");
T_b("\n");
T_b("	");
T_b("0,");
T_b("\n");
T_b("	");
T_b("0);        -- null id");
T_b("\n");
T_b("INSERT INTO DIM_ED");
T_b("\n");
T_b("	");
T_b("VALUES (");
T_b(T_s(coupler->cID1));
T_b(",");
T_b("\n");
T_b("	");
T_b(T_s(coupler->cID2));
T_b(",");
T_b("\n");
T_b("	");
T_b(T_s(widget->ID));
T_b(");         ");
T_b("\n");
T_b("	");
T_b("\n");
