T_b("/*----------------------------------------------------------------------------");
T_b("\n");
T_b(" ");
T_b("* Operation action methods implementation for the following class:");
T_b("\n");
T_b(" ");
T_b("*");
T_b("\n");
T_b(" ");
T_b("* Class:      ");
T_b(te_class->Name);
T_b("  (");
T_b(te_class->Key_Lett);
T_b(")");
T_b("\n");
T_b(" ");
T_b("* Component:  ");
T_b(te_c->Name);
T_b("\n");
T_b(" ");
T_b("*--------------------------------------------------------------------------*/");
T_b("\n");
