T_b("/*");
T_b("\n");
T_b(" ");
T_b("* State-Event Matrix (SEM)");
T_b("\n");
T_b(" ");
T_b("* Row index is object (MC enumerated) current state.");
T_b("\n");
T_b(" ");
T_b("* Row zero is the uninitialized state (e.g., for creation event transitions).");
T_b("\n");
T_b(" ");
T_b("* Column index is (MC enumerated) state machine events.");
T_b("\n");
T_b(" ");
T_b("*/");
T_b("\n");
T_b("static const ");
T_b(te_typemap->SEM_cell_name);
T_b(" ");
T_b(te_sm->SEMname);
T_b("[ ");
T_b(te_sm->num_states);
T_b(" + 1 ][ ");
T_b(num_events);
T_b(" ] = {");
T_b("\n");
T_b("  ");
T_b("/* row 0:  uninitialized state (for creation events) */");
T_b("\n");
T_b(first_row);
T_b("");
T_b(other_rows);
T_b("\n");
T_b("};");
T_b("\n");
