T_b("/*");
T_b("\n");
T_b(" ");
T_b("* Scan the extent for a matching instance.");
T_b("\n");
T_b(" ");
T_b("*/");
T_b("\n");
T_b(te_class->GeneratedName);
T_b(" *");
T_b("\n");
T_b(te_where->select_any_where);
T_b("( ");
T_b(param_list);
T_b(" )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b(te_class->GeneratedName);
T_b(" * ");
T_b(temp_ptr);
T_b("; ");
T_b("\n");
T_b("  ");
T_b(te_set->scope);
T_b(te_set->iterator_class_name);
T_b(" ");
T_b(iterator);
T_b(";");
T_b("\n");
T_b("  ");
T_b(te_set->iterator_reset);
T_b("( &");
T_b(iterator);
T_b(", &");
T_b(extent);
T_b(".");
T_b(te_extent->active);
T_b(" );");
T_b("\n");
T_b("  ");
T_b("while ( (");
T_b(temp_ptr);
T_b(" = (");
T_b(te_class->GeneratedName);
T_b(" *) ");
T_b(te_set->module);
T_b(te_set->iterator_next);
T_b("( &");
T_b(iterator);
T_b(" )) != 0 ) {");
T_b("\n");
T_b("    ");
T_b("if ( ");
T_b(compare_stmt);
T_b(" ) {");
T_b("\n");
T_b("      ");
T_b("return ");
T_b(temp_ptr);
T_b(";");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("return 0;");
T_b("\n");
T_b("}");
T_b("\n");
