T_b(ws);
T_b(te_set->module);
T_b(te_set->clear);
T_b("( ");
T_b(te_select_related->result_var);
T_b(" ); /* ");
T_b(te_select_related->result_var_OAL);
T_b(" (");
T_b(te_class->Key_Lett);
T_b(") */\"");
T_b("\n");
