CC=gcc
CFLAGS=-Wno-pointer-to-int-cast -Wno-parentheses-equality
SOURCES := $(shell ls *.c)
OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=integrity

all:  $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(CFLAGS) $^ -o $@

.o:
	$(CC) $(CFLAGS) -c $<
