T_b("    ");
T_b("for ( int cn=0; cn < ");
T_b(te_dci->max);
T_b("; ++cn ) {");
T_b("\n");
T_b("      ");
T_b(te_instance->factory_init);
T_b("( 0, cn );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
