T_b("/*");
T_b("\n");
T_b(" ");
T_b("* Internal enumerated and structured data types for component:  ");
T_b(te_c->Name);
T_b("\n");
T_b(" ");
T_b("*/");
T_b("\n");
T_b(enumeration_info);
T_b("\n");
T_b(structured_data_types);
T_b("\n");
