T_b("/*----------------------------------------------------------------------------");
T_b("\n");
T_b(" ");
T_b("* File:  ");
T_b(te_ee->file);
T_b(".");
T_b(te_file->src_file_ext);
T_b("\n");
T_b(" ");
T_b("*");
T_b("\n");
T_b(" ");
T_b("* Description:");
T_b("\n");
T_b(" ");
T_b("* Methods for bridging to an external entity.");
T_b("\n");
T_b(" ");
T_b("*");
T_b("\n");
T_b(" ");
T_b("* External Entity:  ");
T_b(te_ee->Name);
T_b(" (");
T_b(te_ee->Key_Lett);
T_b(")");
T_b("\n");
T_b(" ");
T_b("* ");
T_b(te_ee->Descrip);
T_b("\n");
T_b(" ");
T_b("* ");
T_b(te_copyright->body);
T_b("\n");
T_b(" ");
T_b("*--------------------------------------------------------------------------*/");
T_b("\n");
T_b(include_files->body);
T_b("");
T_b("#include \"");
T_b(te_ee->Include_File);
T_b("\"");
T_b("\n");
T_b(includes->body);
T_b("");
T_b(ee_body->body);
T_b("\n");
