T_b("  ");
T_b("/*");
T_b("\n");
T_b("   ");
T_b("* Array of string names of the state machine names.");
T_b("\n");
T_b("   ");
T_b("* Index is the (MC enumerated) number of the state.");
T_b("\n");
T_b("   ");
T_b("*/");
T_b("\n");
T_b("  ");
T_b("static const c_t * const ");
T_b(te_sm->state_names_array);
T_b("[ ");
T_b(state_space);
T_b(" ] = {");
T_b("\n");
T_b("    ");
T_b("\"\",");
T_b("\n");
T_b(state_names);
T_b("");
T_b("  ");
T_b("};");
T_b("\n");
