T_b("#pragma once");
T_b("\n");
T_b("/*");
T_b("\n");
T_b(" ");
T_b("*  register offsets");
T_b("\n");
T_b(" ");
T_b("*");
T_b("\n");
T_b(" ");
T_b("*  Modify base to match your platform.");
T_b("\n");
T_b(" ");
T_b("*/");
T_b("\n");
T_b("#define XTUML_REGISTER_ADDR_BASE 0x0");
T_b("\n");
T_b(register_offset);
T_b("\n");
T_b("/*");
T_b("\n");
T_b(" ");
T_b("*  message orders (commands)");
T_b("\n");
T_b(" ");
T_b("*/");
T_b("\n");
T_b(TLM_message_order);
T_b("\n");
