T_b(ws);
T_b("{ ");
T_b(te_set->scope);
T_b(te_set->iterator_class_name);
T_b(" ");
T_b(iterator);
T_b(";");
T_b("\n");
T_b(ws);
T_b(te_for->class_name);
T_b(" * ");
T_b(current_instance);
T_b(";");
T_b("\n");
T_b(ws);
T_b(te_set->iterator_reset);
T_b("( &");
T_b(iterator);
T_b(", ");
T_b(te_for->set_variable);
T_b(" );");
T_b("\n");
T_b(ws);
T_b("while ( (");
T_b(current_instance);
T_b(" = (");
T_b(te_for->class_name);
T_b(" *)");
T_b(te_set->module);
T_b(te_set->iterator_next);
T_b("( &");
T_b(iterator);
T_b(" )) != 0 ) {");
T_b("\n");
T_b(ws);
T_b("  ");
T_b(te_for->loop_variable);
T_b(" = ");
T_b(current_instance);
T_b("; {");
T_b("\n");
