if ( te_tim->timer_event_search_and_destroy ) {
T_b("/*");
T_b("\n");
T_b(" ");
T_b("* Try to find an event and remove it from the queue.  Dangerous!");
T_b("\n");
T_b(" ");
T_b("* This feature is only reasonable in a single thread.");
T_b("\n");
T_b(" ");
T_b("*/");
T_b("\n");
T_b("bool");
T_b("\n");
T_b(te_eq->search_and_destroy);
T_b("( ");
T_b(te_eq->base_event_type);
T_b(" * event )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("bool rc = false;");
T_b("\n");
T_b("  ");
T_b("OoaEventQueue_t * q = &non_self_event_queue[ 0 ];");
T_b("\n");
T_b("  ");
T_b("/* Assign the event from the head of the queue.  */");
T_b("\n");
T_b("  ");
T_b("if ( ( event != 0 ) && ( q->head != 0 ) ) {");
T_b("\n");
T_b("    ");
T_b("if ( event == q->head ) {");
T_b("\n");
T_b("      ");
T_b("q->head = q->head->next;                          /* unlink */");
T_b("\n");
T_b("      ");
T_b("if ( 0 == q->head ) {");
T_b("\n");
T_b("        ");
T_b("q->tail = 0;");
T_b("\n");
T_b("      ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("} else {");
T_b("\n");
T_b("      ");
T_b(te_eq->base_event_type);
T_b(" * prev = q->head;");
T_b("\n");
T_b("      ");
T_b(te_eq->base_event_type);
T_b(" * cursor;");
T_b("\n");
T_b("      ");
T_b("while ( ( cursor = prev->next ) != event ) {      /* find */");
T_b("\n");
T_b("        ");
T_b("if ( cursor == 0 ) {");
T_b("\n");
T_b("          ");
T_b("return ( false );");
T_b("\n");
T_b("        ");
T_b("}");
T_b("\n");
T_b("        ");
T_b("prev = cursor;");
T_b("\n");
T_b("      ");
T_b("}");
T_b("\n");
T_b("      ");
T_b("prev->next = event->next;                         /* unlink */");
T_b("\n");
T_b("      ");
T_b("if ( cursor == q->head ) {");
T_b("\n");
T_b("        ");
T_b("q->tail = prev;");
T_b("\n");
T_b("      ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("rc = true;");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("return rc;");
T_b("\n");
T_b("}");
T_b("\n");
}
