if ( te_rel->LinkNeeded || te_c->OptDisabled ) {
T_b("/*");
T_b("\n");
T_b(" ");
T_b("* RELATE ");
T_b(super_te_class->Key_Lett);
T_b(" TO ");
T_b(sub_te_class->Key_Lett);
T_b(" ACROSS R");
T_b(te_rel->Numb);
T_b("\n");
T_b(" ");
T_b("*/");
T_b("\n");
T_b("void");
T_b("\n");
T_b(sub_te_class->scope);
T_b(relate_method);
T_b("( ");
T_b(super_te_class->GeneratedName);
T_b(" * supertype, ");
T_b(sub_te_class->GeneratedName);
T_b(" * subtype");
T_b(thismodule);
T_b(" )");
T_b("\n");
T_b("{");
T_b("\n");
if ( te_c->DetectEmpty ) {
T_b("  ");
T_b("if ( (supertype == 0) || (subtype == 0) ) {");
T_b("\n");
T_b("    ");
T_b("XTUML_EMPTY_HANDLE_TRACE( \"");
T_b(sub_te_class->Key_Lett);
T_b("\", \"");
T_b(relate_method);
T_b("\" );");
T_b("\n");
T_b("    ");
T_b("return;");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
} else {
T_b("  ");
T_b("/* Use TagEmptyHandleDetectionOn() to detect empty handle references.  */");
T_b("\n");
}
T_b(set_referentials);
T_b("");
T_b("  ");
T_b("/* Optimized linkage for ");
T_b(sub_te_class->Key_Lett);
T_b("->");
T_b(super_te_class->Key_Lett);
T_b("[R");
T_b(te_rel->Numb);
T_b("] */");
T_b("\n");
T_b("  ");
T_b("subtype->");
T_b(super_te_oir->data_member);
T_b(" = supertype;");
T_b("\n");
T_b("  ");
T_b("/* Optimized linkage for ");
T_b(super_te_class->Key_Lett);
T_b("->");
T_b(sub_te_class->Key_Lett);
T_b("[R");
T_b(te_rel->Numb);
T_b("] */");
T_b("\n");
T_b("  ");
T_b("supertype->");
T_b(sub_te_oir->data_member);
T_b(" = subtype;");
T_b("\n");
T_b("  ");
T_b("supertype->");
T_b(sub_te_oir->object_id);
T_b(" = ");
T_b(sub_te_class->system_class_number);
T_b(";");
T_b("\n");
T_b(persist_relate->body);
T_b("");
T_b("}");
T_b("\n");
}
if ( te_rel->UnlinkNeeded || te_c->OptDisabled ) {
T_b("/*");
T_b("\n");
T_b(" ");
T_b("* UNRELATE ");
T_b(super_te_class->Key_Lett);
T_b(" FROM ");
T_b(sub_te_class->Key_Lett);
T_b(" ACROSS R");
T_b(te_rel->Numb);
T_b("\n");
T_b(" ");
T_b("*/");
T_b("\n");
T_b("void");
T_b("\n");
T_b(sub_te_class->scope);
T_b(unrelate_method);
T_b("( ");
T_b(super_te_class->GeneratedName);
T_b(" * supertype, ");
T_b(sub_te_class->GeneratedName);
T_b(" * subtype");
T_b(thismodule);
T_b(" )");
T_b("\n");
T_b("{");
T_b("\n");
if ( te_c->DetectEmpty ) {
T_b("  ");
T_b("if ( (supertype == 0) || (subtype == 0) ) {");
T_b("\n");
T_b("    ");
T_b("XTUML_EMPTY_HANDLE_TRACE( \"");
T_b(sub_te_class->Key_Lett);
T_b("\", \"");
T_b(unrelate_method);
T_b("\" );");
T_b("\n");
T_b("    ");
T_b("return;");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
} else {
T_b("  ");
T_b("/* Use TagEmptyHandleDetectionOn() to detect empty handle references.  */");
T_b("\n");
}
T_b(reset_referentials);
T_b("");
if ( super_te_oir->NavigatedTo || te_c->OptDisabled ) {
T_b("  ");
T_b("subtype->");
T_b(super_te_oir->data_member);
T_b(" = 0;");
T_b("\n");
} else {
T_b("  ");
T_b("/* Note:  ");
T_b(sub_te_class->Key_Lett);
T_b("->");
T_b(super_te_class->Key_Lett);
T_b("[R");
T_b(te_rel->Numb);
T_b("] not navigated */");
T_b("\n");
}
if ( sub_te_oir->NavigatedTo || te_c->OptDisabled ) {
T_b("  ");
T_b("supertype->");
T_b(sub_te_oir->data_member);
T_b(" = 0;");
T_b("\n");
T_b("  ");
T_b("supertype->");
T_b(sub_te_oir->object_id);
T_b(" = 0;");
T_b("\n");
} else {
T_b("  ");
T_b("/* Note:  ");
T_b(super_te_class->Key_Lett);
T_b("->");
T_b(sub_te_class->Key_Lett);
T_b("[R");
T_b(te_rel->Numb);
T_b("] not navigated */");
T_b("\n");
}
T_b(persist_unrelate->body);
T_b("");
T_b("}");
T_b("\n");
}
