T_b(te_set->scope);
T_b(te_set->base_class);
T_b(" ");
T_b(te_select_related->result_var);
T_b("_space={0}; ");
T_b(te_set->scope);
T_b(te_set->base_class);
T_b(" * ");
T_b(te_select_related->result_var);
T_b(" = &");
T_b(te_select_related->result_var);
T_b("_space; /* ");
T_b(te_select_related->result_var_OAL);
T_b(" (");
T_b(te_class->Key_Lett);
T_b(") */\n");
