CC=gcc
CFLAGS=-DTEMPLATE_ENGINE -Wno-pointer-to-int-cast
SOURCES := $(shell ls *.c)
OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=mcmasl

all:  $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(CFLAGS) $^ -static -l:libfl.a -o $@

.o:
	$(CC) $(CFLAGS) -c $<
