CC=gcc
CFLAGS=-DTEMPLATE_ENGINE -Wno-pointer-to-int-cast
LFLAGS=-l:libfl.a
SOURCES := $(shell ls *.c)
OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=mcmc

all:  $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(CFLAGS) $^ $(LFLAGS) -o $@

.o:
	$(CC) $(CFLAGS) -c $<
