#!/bin/bash

#   ./masl [-v | -vo] < input_file > output_file
#   ./masl [-v | -vo] [ -o <output directory> ] < input_file 

# USAGE
print_usage () { echo "Usage:" $0 "[-v | -vo] [ -o <output directory> ] < input_file"; }

# input variables
VALIDATE=
OUT_DIR=

# parse arguments
DIRECTIVE=
for arg in $@; do
    if [[ ( $arg == "-v" || $arg == "-vo" ) && $VALIDATE == "" ]]; then     # if we encounter a validate flag, set the validation
        VALIDATE=$arg
        DIRECTIVE=                                                          # encounterint a validation flag resets the directive because
    elif [[ $arg == "-o" ]]; then                                           # set the directive
        DIRECTIVE=$arg
    elif [[ $DIRECTIVE == "-o" && $OUT_DIR == "" ]]; then                   # only can set the output directory once
        OUT_DIR=$arg
    else
        print_usage
        exit 1
    fi
done

# if no out directory was given, give the current working directory
if [[ $OUT_DIR == "" ]]; then OUT_DIR=.; fi

# only produce output if -vo is not set
if [[ $VALIDATE != "-vo" ]]; then
    DIR=$OUT_DIR/masl_files_$RANDOM
    mkdir $DIR
    cat > $DIR/maslfile.masl
fi
