#!/bin/sh

# check arguments
if [ "$#" -gt 1 ]; then
    echo "Usage:" $0 "[-p | -d] < input_file > output_file"
    exit 1
elif [ "$#" -eq 1 ] && [ "$1" != "-p" ] && [ "$1" != "-d" ]; then
    echo "Usage:" $0 "[-p | -d] < input_file > output_file"
    exit 1
fi

# redirect stdin to stdout
cat
