#!/bin/sh

#   ./maslvalidate [-p <project source directory(s) ...> ] \
#       [-d <domain source directory(s) ...> ]


# USAGE
print_usage () { echo "Usage:" $0 "[-p <project source directory(s) ...> ] [-d <domain source directory(s) ...> ]"; }

# set up paths
export PATH=$PATH:`cat path`
CLASSPATH=`cat classpath`

# input variables
PROJ_DIRS=()
DOM_DIRS=()

# parse arguments
DIRECTIVE=
for arg in $@; do
    if [[ $arg == "-p" || $arg == "-d" ]]; then                     # set the directive
        DIRECTIVE=$arg
    elif [[ $DIRECTIVE == "-p" ]]; then                             # add a project dir
        PROJ_DIRS+=($arg)
    elif [[ $DIRECTIVE == "-d" ]]; then                             # add a domain dir
        DOM_DIRS+=($arg)
    else
        print_usage
        exit 1
    fi
done

# echo Args:
# echo PROJ_DIRS=${PROJ_DIRS[*]}
# echo DOM_DIRS=${DOM_DIRS[*]}
# exit 0

# process domains
for domain in ${DOM_DIRS[*]}; do
    #echo "java -cp $CLASSPATH MaslImportParser -d $domain | masl -vo"
    java -cp $CLASSPATH MaslImportParser -d $domain | masl -vo
done

# process projects
for project in ${PROJ_DIRS[*]}; do
    #echo "java -cp $CLASSPATH MaslImportParser -p $project | masl -vo"
    java -cp $CLASSPATH MaslImportParser -p $project | masl -vo
done
