T_b("  ");
T_b("/*");
T_b("\n");
T_b("   ");
T_b("* Array of pointers to the class transition action procedures.");
T_b("\n");
T_b("   ");
T_b("* Index is the (MC enumerated) number of the transition action to execute.");
T_b("\n");
T_b("   ");
T_b("*/");
T_b("\n");
T_b("  ");
T_b("static const ");
T_b(te_sm->action_type);
T_b(" ");
T_b(te_sm->txn_action_array);
T_b("[ ");
T_b(num_te_acts);
T_b(" ] = {");
T_b("\n");
T_b(txn_action_rows);
T_b("");
T_b("  ");
T_b("};");
T_b("\n");
