T_b("  ");
T_b("/*");
T_b("\n");
T_b("   ");
T_b("* Array of pointers to the class state action procedures.");
T_b("\n");
T_b("   ");
T_b("* Index is the (MC enumerated) number of the state action to execute.");
T_b("\n");
T_b("   ");
T_b("*/");
T_b("\n");
T_b("  ");
T_b("static const ");
T_b(te_sm->action_type);
T_b(" ");
T_b(te_sm->action_array);
T_b("[ ");
T_b(state_space);
T_b(" ] = {");
T_b("\n");
T_b("    ");
T_b("(");
T_b(te_sm->action_type);
T_b(") 0,");
T_b("\n");
T_b(state_action_rows);
T_b("");
T_b("  ");
T_b("};");
T_b("\n");
