T_b("/*---------------------------------------------------------------------------");
T_b("\n");
T_b(" ");
T_b("* File:  ");
T_b(te_file->xtumlload);
T_b(".");
T_b(te_file->src_file_ext);
T_b("\n");
T_b(" ");
T_b("*");
T_b("\n");
T_b(" ");
T_b("* Description:");
T_b("\n");
T_b(" ");
T_b("*   This module receives the string format instance data, converts it");
T_b("\n");
T_b(" ");
T_b("*   and loads instances into memory.");
T_b("\n");
T_b(" ");
T_b("*   It parse xtUML SQL files as input.");
T_b("\n");
T_b(" ");
T_b("*");
T_b("\n");
T_b(" ");
T_b("* ");
T_b(te_copyright->body);
T_b("\n");
T_b(" ");
T_b("*--------------------------------------------------------------------------*/");
T_b("\n");
T_b("#include \"");
T_b(te_file->types);
T_b(".");
T_b(te_file->hdr_file_ext);
T_b("\"");
T_b("\n");
T_b("#include \"");
T_b(te_file->xtumlload);
T_b(".");
T_b(te_file->hdr_file_ext);
T_b("\"");
T_b("\n");
T_b(all_domain_include_files);
T_b("\n");
T_b("typedef ");
T_b(te_instance->handle);
T_b(" (*LoadInstance_t)( ");
T_b(te_instance->handle);
T_b(", const c_t * [] );");
T_b("\n");
T_b("typedef struct {");
T_b("\n");
T_b("  ");
T_b("const c_t * s;");
T_b("\n");
T_b("  ");
T_b("const Escher_ClassNumber_t class_number;");
T_b("\n");
T_b("  ");
T_b("const LoadInstance_t instance_loader;");
T_b("\n");
T_b("} Escher_instance_loader_info_t;");
T_b("\n");
T_b("Escher_instance_loader_info_t class_string_2_class_number[] = {");
T_b("\n");
T_b(all_instance_loaders);
T_b("");
T_b("};");
T_b("\n");
T_b("static Escher_ClassNumber_t lookupclassloader( const c_t * );");
T_b("\n");
T_b("static Escher_ClassNumber_t lookupclassloader( const c_t * s )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("Escher_ClassNumber_t i;");
T_b("\n");
T_b("  ");
T_b("/* Search on class key letters to get class number.  */");
T_b("\n");
T_b("  ");
T_b("for ( i = 0; i < sizeof( class_string_2_class_number ) / sizeof( Escher_instance_loader_info_t ); i++ ) {");
T_b("\n");
T_b("    ");
T_b("if ( 0 == Escher_strcmp( s, class_string_2_class_number[ i ]->s ) ) {");
T_b("\n");
T_b("      ");
T_b("break;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("return i;");
T_b("\n");
T_b("}");
T_b("\n");
T_b("static void Escher_load_instance( Escher_ClassNumber_t, const c_t * [] );");
T_b("\n");
T_b("static void Escher_load_instance(");
T_b("\n");
T_b("  ");
T_b("Escher_ClassNumber_t count,");
T_b("\n");
T_b("  ");
T_b("const c_t * wordvalues[]");
T_b("\n");
T_b(")");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("Escher_ClassNumber_t n;");
T_b("\n");
T_b("  ");
T_b(te_instance->handle);
T_b(" instance;");
T_b("\n");
T_b("  ");
T_b(te_instance->handle);
T_b(" return_identifier;");
T_b("\n");
T_b("  ");
T_b("/* Look up the class number and instance loader using the key letters.  */");
T_b("\n");
T_b("  ");
T_b("n = lookupclassloader( wordvalues[ 0 ] );");
T_b("\n");
T_b("  ");
T_b("/* Invoke the creation function using the class number.  */");
T_b("\n");
T_b("  ");
T_b("instance = Escher_CreateInstance(");
T_b("\n");
T_b("    ");
T_b("0, class_string_2_class_number[n].class_number );");
T_b("\n");
T_b("  ");
T_b("/* Convert/Populate the attribute values.  */");
T_b("\n");
T_b("  ");
T_b("return_identifier = (*class_string_2_class_number[n].instance_loader)( instance, wordvalues );");
T_b("\n");
T_b("  ");
T_b("if ( 0 != return_identifier ) {");
T_b("\n");
T_b("    ");
T_b("Escher_instance_cache[ (intptr_t) return_identifier ] = instance;");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("}");
T_b("\n");
T_b("/*");
T_b("\n");
T_b("   ");
T_b("xtUML Parser Grammar");
T_b("\n");
T_b("   ");
T_b("statement        : ( comment )* | insert_statement");
T_b("\n");
T_b("   ");
T_b("comment          : \"--\" [^\n]*");
T_b("\n");
T_b("   ");
T_b("insert_statement : \"INSERT INTO\" keyletters \"VALUES\" \"(\" values \")\" \";\"");
T_b("\n");
T_b("   ");
T_b("keyletters       : [a-zA-Z][a-zA-Z0-9_]*");
T_b("\n");
T_b("   ");
T_b("values           : ( value comma )*   // cheat a bit allowing extra commas");
T_b("\n");
T_b("   ");
T_b("value            : unique_id | number | stringvalue");
T_b("\n");
T_b("   ");
T_b("unique_id        : '\"' [0-9a-f-]+ '\"'");
T_b("\n");
T_b("   ");
T_b("number           : [0-9-]+");
T_b("\n");
T_b("   ");
T_b("stringvalue    : \"'\" [^']* \"'\"   // unless escaped with ''");
T_b("\n");
T_b("*/");
T_b("\n");
T_b("static void init( void );");
T_b("\n");
T_b("static bool readrecord( char ** );");
T_b("\n");
T_b("/* parser */");
T_b("\n");
T_b("static bool statement( void );");
T_b("\n");
T_b("static bool comment( void );");
T_b("\n");
T_b("static bool insert_statement( void );");
T_b("\n");
T_b("static bool keyletters( void );");
T_b("\n");
T_b("static bool values( void );");
T_b("\n");
T_b("static bool value( void );");
T_b("\n");
T_b("static bool comma( void );");
T_b("\n");
T_b("static bool unique_id( void );");
T_b("\n");
T_b("static bool number( void );");
T_b("\n");
T_b("static bool stringvalue( void );");
T_b("\n");
T_b("static void whitespace( void );");
T_b("\n");
T_b("static bool parsestring( c_t * );");
T_b("\n");
T_b("static FILE * xtumlfile;");
T_b("\n");
T_b("static c_t * cursor;");
T_b("\n");
T_b("#define MAXWORDS 250");
T_b("\n");
T_b("static const c_t * word[ MAXWORDS ];");
T_b("\n");
T_b("static Escher_ClassNumber_t wordindex;");
T_b("\n");
T_b("/*");
T_b("\n");
T_b("#define DEVELOPER_DEBUG( s, c ) printf( s, c );");
T_b("\n");
T_b("*/");
T_b("\n");
T_b("#define DEVELOPER_DEBUG( s, c )");
T_b("\n");
T_b("/*");
T_b("\n");
T_b(" ");
T_b("* Loop through reading the file one record at a time.");
T_b("\n");
T_b(" ");
T_b("* Parse each record.");
T_b("\n");
T_b(" ");
T_b("*/");
T_b("\n");
T_b("int Escher_xtUML_load(");
T_b("\n");
T_b("  ");
T_b("int argc,");
T_b("\n");
T_b("  ");
T_b("char * argv[]");
T_b("\n");
T_b(")");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("Escher_ClassNumber_t i;");
T_b("\n");
T_b("  ");
T_b("bool done = false;");
T_b("\n");
T_b("  ");
T_b("if ( 2 != argc ) {");
T_b("\n");
T_b("    ");
T_b("printf( \"xtumlload <input xtUML file>\n\" );");
T_b("\n");
T_b("    ");
T_b("return 1;");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("if ( (xtumlfile = fopen( argv[1], \"r\" )) == 0 ) {");
T_b("\n");
T_b("    ");
T_b("printf( \"%s failed to open %s\n\", argv[0], argv[1] );");
T_b("\n");
T_b("    ");
T_b("return 1;");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("init();               /* Initialize the xml storage area.      */");
T_b("\n");
T_b("  ");
T_b("printf( \"-- Read %s on the %s command line.\n\", argv[1], argv[0] );");
T_b("\n");
T_b("  ");
T_b("/*");
T_b("\n");
T_b("   ");
T_b("* Read a record.  Parse it.  Pass it.  Repeat until end of file.");
T_b("\n");
T_b("   ");
T_b("*/");
T_b("\n");
T_b("  ");
T_b("while ( ! done ) {");
T_b("\n");
T_b("    ");
T_b("done = readrecord( &cursor );");
T_b("\n");
T_b("    ");
T_b("if ( statement() ) {");
T_b("\n");
T_b("      ");
T_b("if ( 0 != wordindex ) {");
T_b("\n");
T_b("        ");
T_b("Escher_load_instance( wordindex, word );");
T_b("\n");
T_b("      ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("} else {");
T_b("\n");
T_b("      ");
T_b("printf( \"Error:  Did not parse.\n\" );");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("for ( i = 0; i < ");
T_b(all_max_class_numbers);
T_b("; i++ ) {");
T_b("\n");
T_b("    ");
T_b("Escher_batch_relate( 0, i );");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("return 0;");
T_b("\n");
T_b("}");
T_b("\n");
T_b("/*");
T_b("\n");
T_b(" ");
T_b("* Initialize the buffers and pointers.");
T_b("\n");
T_b(" ");
T_b("*/");
T_b("\n");
T_b("static void init( void )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("for ( wordindex = 0; wordindex < MAXWORDS; wordindex++ ) {");
T_b("\n");
T_b("    ");
T_b("word[ wordindex ] = 0;");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("wordindex = 0;");
T_b("\n");
T_b("}");
T_b("\n");
T_b("/*");
T_b("\n");
T_b(" ");
T_b("* Read a record from the file.");
T_b("\n");
T_b(" ");
T_b("*/");
T_b("\n");
T_b("static bool readrecord( c_t ** r )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("#define MAXRECORDLENGTH 400000");
T_b("\n");
T_b("  ");
T_b("static c_t record[ MAXRECORDLENGTH ] = {0};");
T_b("\n");
T_b("  ");
T_b("#define MAXLINELENGTH 1000");
T_b("\n");
T_b("  ");
T_b("static c_t line[ MAXLINELENGTH ] = {0};");
T_b("\n");
T_b("  ");
T_b("bool done = false;");
T_b("\n");
T_b("  ");
T_b("bool last_record = false;");
T_b("\n");
T_b("  ");
T_b("c_t * p = record;");
T_b("\n");
T_b("  ");
T_b("*r = record;");
T_b("\n");
T_b("  ");
T_b("/* Add the line to record.  On the first read, this will be a NOP.");
T_b("\n");
T_b("     ");
T_b("On all other reads, this will get the front part of the record");
T_b("\n");
T_b("     ");
T_b("(INSERT INTO) that we read the last time. */");
T_b("\n");
T_b("  ");
T_b("strncpy( p, line, MAXLINELENGTH );");
T_b("\n");
T_b("  ");
T_b("p = p + Escher_strlen( line );");
T_b("\n");
T_b("  ");
T_b("while ( ! done ) {");
T_b("\n");
T_b("    ");
T_b("if ( fgets( line, MAXLINELENGTH, xtumlfile ) == 0 ) {");
T_b("\n");
T_b("      ");
T_b("done = true;");
T_b("\n");
T_b("      ");
T_b("last_record = true;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("/* Note that we only compare as much as we care about.  */");
T_b("\n");
T_b("    ");
T_b("if ( 0 != strncmp( line, \"INSERT INTO \", 12 ) ) {");
T_b("\n");
T_b("      ");
T_b("strncpy( p, line, MAXLINELENGTH );");
T_b("\n");
T_b("      ");
T_b("p = p + Escher_strlen( line );");
T_b("\n");
T_b("      ");
T_b("line[ 0 ] = 0;");
T_b("\n");
T_b("    ");
T_b("} else {");
T_b("\n");
T_b("      ");
T_b("done = true;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("return last_record;");
T_b("\n");
T_b("}");
T_b("\n");
T_b("static bool statement( void )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("s4_t commentsfound = 0;");
T_b("\n");
T_b("  ");
T_b("DEVELOPER_DEBUG( \"statement %s\n\", cursor );");
T_b("\n");
T_b("  ");
T_b("word[ 0 ] = \"\";");
T_b("\n");
T_b("  ");
T_b("wordindex = 0;");
T_b("\n");
T_b("  ");
T_b("while ( comment() ) commentsfound++;");
T_b("\n");
T_b("  ");
T_b("return ( insert_statement() || ( commentsfound > 0 ) );");
T_b("\n");
T_b("}");
T_b("\n");
T_b("static bool comment( void )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("s4_t guard_counter = 0;");
T_b("\n");
T_b("  ");
T_b("DEVELOPER_DEBUG( \"comment %s\n\", cursor );");
T_b("\n");
T_b("  ");
T_b("whitespace();");
T_b("\n");
T_b("  ");
T_b("if ( ! parsestring( \"--\" ) ) return false;");
T_b("\n");
T_b("  ");
T_b("do {");
T_b("\n");
T_b("    ");
T_b("cursor++;");
T_b("\n");
T_b("  ");
T_b("} while ( ( *cursor != '\n' ) && ( guard_counter++ < MAXLINELENGTH ) );");
T_b("\n");
T_b("  ");
T_b("return true;");
T_b("\n");
T_b("}");
T_b("\n");
T_b("static bool insert_statement( void )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("DEVELOPER_DEBUG( \"insert_statement %s\n\", cursor );");
T_b("\n");
T_b("  ");
T_b("whitespace();");
T_b("\n");
T_b("  ");
T_b("if ( ! parsestring( \"INSERT\" ) ) return false;");
T_b("\n");
T_b("  ");
T_b("if ( ! parsestring( \"INTO\" ) ) return false;");
T_b("\n");
T_b("  ");
T_b("if ( ! keyletters() ) return false;");
T_b("\n");
T_b("  ");
T_b("if ( ! parsestring( \"VALUES\" ) ) return false;");
T_b("\n");
T_b("  ");
T_b("if ( ! parsestring( \"(\" ) ) return false;");
T_b("\n");
T_b("  ");
T_b("values();");
T_b("\n");
T_b("  ");
T_b("if ( ')' != *cursor ) return false;");
T_b("\n");
T_b("  ");
T_b("*cursor++ = 0;   /* Zero out parenthesis to serve as delimeter.  */");
T_b("\n");
T_b("  ");
T_b("if ( ';' != *cursor ) return false;");
T_b("\n");
T_b("  ");
T_b("cursor++;");
T_b("\n");
T_b("  ");
T_b("return true;");
T_b("\n");
T_b("}");
T_b("\n");
T_b(" ");
T_b(" ");
T_b("\n");
T_b("static bool keyletters( void )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("DEVELOPER_DEBUG( \"keyletters() %s\n\", cursor );");
T_b("\n");
T_b("  ");
T_b("whitespace();");
T_b("\n");
T_b("  ");
T_b("if ( ! ( ( ( 'a' <= *cursor ) && ( *cursor <= 'z' ) ) ||");
T_b("\n");
T_b("           ");
T_b("( ( 'A' <= *cursor ) && ( *cursor <= 'Z' ) ) ) ) {");
T_b("\n");
T_b("    ");
T_b("return false;");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("/* Capture keyletters here.  */");
T_b("\n");
T_b("  ");
T_b("word[ wordindex++ ] = cursor++;");
T_b("\n");
T_b("  ");
T_b("while ( ( ( 'a' <= *cursor ) && ( *cursor <= 'z' ) ) ||");
T_b("\n");
T_b("          ");
T_b("( ( 'A' <= *cursor ) && ( *cursor <= 'Z' ) ) ||");
T_b("\n");
T_b("          ");
T_b("( ( '0' <= *cursor ) && ( *cursor <= '9' ) ) ||");
T_b("\n");
T_b("          ");
T_b("( *cursor == '_' ) ||");
T_b("\n");
T_b("          ");
T_b("( *cursor == '-' ) ) {");
T_b("\n");
T_b("    ");
T_b("cursor++;");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("*cursor++ = 0;   /* Delimit key letters (overwriting white space).  */");
T_b("\n");
T_b("  ");
T_b("return true;");
T_b("\n");
T_b("}");
T_b("\n");
T_b("static bool values( void )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("DEVELOPER_DEBUG( \"values() %s\n\", cursor );");
T_b("\n");
T_b("  ");
T_b("/* Cheat here a little and allow leading and/or trailing commas.  */");
T_b("\n");
T_b("  ");
T_b("while ( comma() || value() ) ;");
T_b("\n");
T_b("  ");
T_b("return true;");
T_b("\n");
T_b("}");
T_b("\n");
T_b("static bool value( void )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("DEVELOPER_DEBUG( \"value() %s\n\", cursor );");
T_b("\n");
T_b("  ");
T_b("if ( ! ( unique_id() || number() || stringvalue() ) ) return false;");
T_b("\n");
T_b("  ");
T_b("word[ wordindex ] = cursor; /* mark end of element */");
T_b("\n");
T_b("  ");
T_b("return true;");
T_b("\n");
T_b("}");
T_b("\n");
T_b("static bool comma( void )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("DEVELOPER_DEBUG( \"comma() %s\n\", cursor );");
T_b("\n");
T_b("  ");
T_b("whitespace();");
T_b("\n");
T_b("  ");
T_b("if ( ',' != *cursor ) return false;");
T_b("\n");
T_b("  ");
T_b("*cursor++ = 0;   /* Zero out comma to serve as delimeter.  */");
T_b("\n");
T_b("  ");
T_b("return true;");
T_b("\n");
T_b("}");
T_b("\n");
T_b("static bool unique_id( void )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("s4_t guard_counter = 0;");
T_b("\n");
T_b("  ");
T_b("DEVELOPER_DEBUG( \"unique_id() %s\n\", cursor );");
T_b("\n");
T_b("  ");
T_b("if ( ! ( '\"' == *cursor ) ) return false;");
T_b("\n");
T_b("  ");
T_b("cursor++;   /* Eat the quotation mark.  */");
T_b("\n");
T_b("  ");
T_b("/* Capture unique_id into word.  */");
T_b("\n");
T_b("  ");
T_b("word[ wordindex++ ] = cursor++;");
T_b("\n");
T_b("  ");
T_b("while ( ( ( ( '0' <= *cursor ) && ( *cursor <= '9' ) ) ||");
T_b("\n");
T_b("            ");
T_b("( ( 'a' <= *cursor ) && ( *cursor <= 'z' ) ) ||");
T_b("\n");
T_b("            ");
T_b("( *cursor == '-' ) ) &&");
T_b("\n");
T_b("          ");
T_b("( guard_counter++ < MAXLINELENGTH ) ) {");
T_b("\n");
T_b("    ");
T_b("cursor++;");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("*cursor++ = 0;  /* Overwrite trailing quotation mark with delimter.  */");
T_b("\n");
T_b("  ");
T_b("return true;");
T_b("\n");
T_b("}");
T_b("\n");
T_b("static bool number( void )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("s4_t guard_counter = 0;");
T_b("\n");
T_b("  ");
T_b("DEVELOPER_DEBUG( \"number() %s\n\", cursor );");
T_b("\n");
T_b("  ");
T_b("if ( ! ( ( ( '0' <= *cursor ) && ( *cursor <= '9' ) ) ||");
T_b("\n");
T_b("           ");
T_b("( *cursor == '-' ) ) ) return false;");
T_b("\n");
T_b("  ");
T_b("/* Capture unique_id into word.  */");
T_b("\n");
T_b("  ");
T_b("word[ wordindex++ ] = cursor++;");
T_b("\n");
T_b("  ");
T_b("while ( ( ( ( '0' <= *cursor ) && ( *cursor <= '9' ) ) ||");
T_b("\n");
T_b("            ");
T_b("( *cursor == '-' ) ) &&");
T_b("\n");
T_b("          ");
T_b("( guard_counter++ < MAXLINELENGTH ) ) {");
T_b("\n");
T_b("    ");
T_b("cursor++;");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("return true;");
T_b("\n");
T_b("}");
T_b("\n");
T_b("static bool stringvalue( void )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("s4_t guard_counter = 0;");
T_b("\n");
T_b("  ");
T_b("DEVELOPER_DEBUG( \"stringvalue() %s\n\", cursor );");
T_b("\n");
T_b("  ");
T_b("if ( *cursor != '\'' ) return false;");
T_b("\n");
T_b("  ");
T_b("cursor++;");
T_b("\n");
T_b("  ");
T_b("/* Capture unique_id into word.  */");
T_b("\n");
T_b("  ");
T_b("word[ wordindex++ ] = cursor;");
T_b("\n");
T_b("  ");
T_b("/* The following if statement deals with empty strings->  */");
T_b("\n");
T_b("  ");
T_b("if ( ( *cursor != '\'' ) || ( *(cursor + 1) == '\'' ) ) {");
T_b("\n");
T_b("    ");
T_b("while ( guard_counter++ < MAXRECORDLENGTH ) {");
T_b("\n");
T_b("      ");
T_b("if ( ( *cursor == '\'' ) && ( *(cursor + 1) == '\'' ) ) {");
T_b("\n");
T_b("        ");
T_b("cursor++;");
T_b("\n");
T_b("        ");
T_b("cursor++;");
T_b("\n");
T_b("      ");
T_b("} else if ( ( *cursor == '\'' ) && ( *(cursor + 1) != '\'' ) ) {");
T_b("\n");
T_b("        ");
T_b("break;");
T_b("\n");
T_b("      ");
T_b("} else {");
T_b("\n");
T_b("        ");
T_b("cursor++;");
T_b("\n");
T_b("      ");
T_b("}");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("*cursor++ = 0;  /* Overwrite trailing quotation mark with delimter.  */");
T_b("\n");
T_b("  ");
T_b("return true;");
T_b("\n");
T_b("}");
T_b("\n");
T_b("static bool parsestring(");
T_b("\n");
T_b("  ");
T_b("c_t * s1");
T_b("\n");
T_b(")");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("c_t * s2;");
T_b("\n");
T_b("  ");
T_b("whitespace();");
T_b("\n");
T_b("  ");
T_b("s2 = cursor;");
T_b("\n");
T_b("  ");
T_b("while ( *s1++ == *s2++ ) {");
T_b("\n");
T_b("    ");
T_b("if ( 0 == *s1 ) {");
T_b("\n");
T_b("      ");
T_b("cursor = s2;");
T_b("\n");
T_b("      ");
T_b("return true;");
T_b("\n");
T_b("    ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("  ");
T_b("return false;");
T_b("\n");
T_b("}");
T_b("\n");
T_b("static void whitespace( void )");
T_b("\n");
T_b("{");
T_b("\n");
T_b("  ");
T_b("s4_t guard_counter = 0;");
T_b("\n");
T_b("  ");
T_b("while ( ( ( *cursor == ' ' ) ||");
T_b("\n");
T_b("            ");
T_b("( *cursor == '\r' ) ||");
T_b("\n");
T_b("            ");
T_b("( *cursor == '\n' ) ||");
T_b("\n");
T_b("            ");
T_b("( *cursor == '\t' ) ) &&");
T_b("\n");
T_b("          ");
T_b("( guard_counter++ < MAXLINELENGTH ) ) {");
T_b("\n");
T_b("    ");
T_b("cursor++;");
T_b("\n");
T_b("  ");
T_b("}");
T_b("\n");
T_b("}");
T_b("\n");
