T_b("#ifndef SYS_XTUMLLOAD_H");
T_b("\n");
T_b("#define SYS_XTUMLLOAD_H");
T_b("\n");
T_b(te_target->c2cplusplus_linkage_begin);
T_b("\n");
T_b("int Escher_xtUML_load( int, char * [] );");
T_b("\n");
T_b(te_target->c2cplusplus_linkage_end);
T_b("\n");
T_b("#endif   /* SYS_XTUMLLOAD_H */");
T_b("\n");
