= Parse and Load MASL Activity

xtUML Project Design Note

== 1 Abstract

MASL action language shall be parsed and loaded into an xtUML model of
MASL activity.  This note documents design steps to achieve this parsing.

== 2 Introduction and Background


== 3 Requirements


== 4 Analysis

== 5 Design

. Review the MASL Reference Manual
  .. Identify structural constructs linked to statements and expressions
     that are available in MASL only.
  .. Determine the means and cost of supporting these constructs.
  .. Identify potential blockers.


== 6 Design Comments

== 7 User Documentation

Describe the end user documentation that was added for this change.

== 8 Unit Test

Outline all the unit tests that need to pass and describe the method that you
will use to design and perform the tests.


== 9 Document References

. [[dr-1]] https://support.onefact.net/issues/11745[11745 - Parse MASL into xtUML meta-model of MASL activity]
. [[dr-2]] https://support.onefact.net/issues/11744[11744 - AWS software architecture]

---

This work is licensed under the Creative Commons CC0 License

---
