#!/bin/bash

#   ./xtuml2masl [-v | -vo] [-p <xtUML file(s) ...> ] [-d <xtUML file(s) ...> ] \
#       [ -o <output directory> ]

# USAGE
print_usage () { echo "Usage:" $0 "[-v | -vo] [-p <xtUML file(s) ...> ] [-d <xtUML file(s) ...> ] [ -o <output directory> ]"; }

# set up path
export PATH=$PATH:../lib

# input variables
VALIDATE=
PROJ_FILES=()
DOM_FILES=()
OUT_DIR=

# parse arguments
DIRECTIVE=
for arg in $@; do
    if [[ ( $arg == "-v" || $arg == "-vo" ) && $VALIDATE == "" ]]; then     # if we encounter a validate flag, set the validation
        VALIDATE=$arg
        DIRECTIVE=                                                          # encounterint a validation flag resets the directive because
    elif [[ $arg == "-p" || $arg == "-d" || $arg == "-o" ]]; then           # set the directive
        DIRECTIVE=$arg
    elif [[ $DIRECTIVE == "-p" ]]; then                                     # add a project file
        PROJ_FILES+=($arg)
    elif [[ $DIRECTIVE == "-d" ]]; then                                     # add a domain file
        DOM_FILES+=($arg)
    elif [[ $DIRECTIVE == "-o" && $OUT_DIR == "" ]]; then                   # only can set the output directory once
        OUT_DIR=$arg
    else
        print_usage
        exit 1
    fi
done

# if no out directory was given, give the current working directory
if [[ $OUT_DIR == "" ]]; then OUT_DIR=.; fi

# echo Args:
# echo VALIDATE=$VALIDATE
# echo PROJ_FILES=${PROJ_FILES[*]}
# echo DOM_FILES=${DOM_FILES[*]}
# echo OUT_DIR=$OUT_DIR

# make the output directory if ther is one
if [[ $OUT_DIR != "" ]]; then
    if ! mkdir -p $OUT_DIR; then
        echo "-masl2xtuml: ERROR could not create directory '$OUT_DIR'" 1>&2
        exit 1
    fi
fi

# process domains
for domain in ${DOM_FILES[*]}; do
    #echo "cat $domain | x2m -d | masl $VALIDATE -o $OUT_DIR"
    cat $domain | x2m -d | masl $VALIDATE -o $OUT_DIR
done

# process projects
for project in ${PROJ_FILES[*]}; do
    #echo "cat $project | x2m -p | masl $VALIDATE -o $OUT_DIR"
    cat $project | x2m -p | masl $VALIDATE -o $OUT_DIR
done
